title: Jonathan E. Prunty # your name (or website title) here
logo: "/images/profilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Cognitive Scientist<br>
  Developmental psychology, social cognition, perception, and Autism Spectrum Disorder
  <br><br>
  Data Scientist<br>
  Python, R and Matlab for machine learning, healthcare analytics, and research methods development
  <br><br>
  <a href="https://scholar.google.com/citations?user=ubmJ2nsAAAAJ&hl=en">Google Scholar</a> 
  <br><br>
  <a href="https://orcid.org/0000-0002-9180-1932">Orcid</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/jonathan-prunty-22866aba/">LinkedIn</a> 
  <br><br>
  <a href="https://github.com/JonnyP1990">LinkedIn</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: G-L9GXXB3WDV
